data:
  corpus:                                 # Pass to dataloader
    # The following depends on corpus
    name: 'DLHLP'                         # Specify corpus
    path: '/work/b07u1234/b06502162/HW1-2/HW1-2/DLHLP'
    dev_split: ['dev']
    test_split: ['test']
    bucketing: False
    batch_size: 1
src:
  config: '/work/b07u1234/b07701209/E2E_ASR_TWCC/config/dlhlp_asr_best3.yaml'
  ckpt: '/work/b07u1234/b07701209/model_dir/ckpt/transform_time_only/best_att_dev.pth'

decode:
  beam_size: 1
  min_len_ratio: 0.01
  max_len_ratio: 0.30
  lm_path: /work/b07u1234/b06502162/HW1-2/ckpt/dim_256/best_ppx.pth
  lm_config: '/work/b07u1234/b06502162/HW1-2/HW1-2/config/dlhlp_lm.yaml'
  lm_weight: 0.7
  ctc_weight: 0
